name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install 📦
        uses: bahmutov/npm-install@1

      - name: Linting 🧹
        run: npm run lint

      - name: Run tests 🧪
        run: npm test

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        env:
          DEBUG: simple
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
